cadastro_usuarios/urls.py
# Django
from django.urls import path
# Views
from . import views

app_name = 'cadastro_usuarios'

urlpatterns = [
    path('', views.home, name='home'),
    path('cria_usuario/', views.cria_usuarios, name='cria_usuarios'), # type: ignore
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'), # type: ignore
    path('delete_usuario/', views.deleta_usuarios, name='delete_usuarios'), # type: ignore
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cadastro_usuarios.urls')),
    path('admin/', admin.site.urls),
]

cadastro_usuarios/models.py
from django.db import models

# Create your models here.
class Usuario(models.Model):
    nome = models.TextField(max_length=255)
    idade = models.IntegerField()


    def __str__(self):
        return f'Objeto: {self.nome} do Modelo: {self.__class__.__name__}'

cadastro_usuarios/views.py
# Django
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http.response import HttpResponse
# Models
from .models import Usuario


# Create your views here.
def home(request):
    # TODO: Renderizar um formulário Django para html HOME

    return render(
        request,
        'usuarios/home.html',
    )


def cria_usuarios(request):
    new_user = Usuario()

    if not request.POST:
        return HttpResponse('Requisição inválida!')
    
    new_user.nome = request.POST.get('nome')
    new_user.idade = request.POST.get('idade')
    new_user.save()

    return redirect(reverse('cadastro_usuarios:lista_usuarios'))


def lista_usuarios(request):
    user = Usuario.objects.all()

    ctx = {
        'usuarios': user
    }

    return render(
        request,
        'usuarios/usuarios.html',
        context=ctx
    )


def deleta_usuarios(request, pk):
    user = Usuario.objects.filter(pk=pk).first()
    user.delete() #type: ignore

    return redirect(reverse('cadastro_usuarios:lista_usuarios'))

cadastro_usuarios/templates/usuarios/home.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <title>Cadastre-me!</title>
</head>

<body>
  <!--Navbar-->
  <nav style="background-color: aquamarine !important;" class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand mb-0 h1" href="">Cadastre-me!</a>
    </div>
  </nav>

  <!--Formulário para cadastro de usuário-->
  <form action="{% url 'cadastro_usuarios:cria_usuarios' %}" method="POST">
    {% csrf_token %}
    <div style="text-align: center;" class="container">
      <h1>Cadastro de usuários</h1>
      Nome: <input class="form-control-sm" type="text" name="nome">
      Idade: <input class="form-control-sm" type="text" name="idade">

      <button class="form-control-sm" type="submit">Enviar</button>
    </div>
  </form>


  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

cadastro_usuarios/templates/usuarios/usuarios.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Cadastre-me!</title>
</head>

<body>

    <!--Navbar-->
    <nav style="background-color: aquamarine !important;" class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand mb-0 h1" href="{% url 'cadastro_usuarios:home' %}">Cadastre-me!</a>
        </div>
    </nav>

    <div class="container">
        <table class="table table-bordered table-striped">
            <tr>
                <th>id</th>
                <th>nome</th>
                <th>idade</th>
            </tr>

            {% for usuario in usuarios %}
            <tr>
                <td> {{ usuario.pk }} </td>
                <td> {{ usuario.nome }} </td>
                <td> {{ usuario.idade }} </td>
            </tr>
            {% endfor %}

        </table>
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
      -->
</body>

</html>